### PR TITLE
OpenCL Implementation

### PR DESCRIPTION
**Pull request by colonelwatch**
I think I've built up enough of this new OpenCL feature that it can be merged into master now. Merging will mean that I can dedicate my attention to nonceMiner as a whole again.
- Performance is decent, though I'm baffled at how @DoctorEenot managed 3 GH/s on the same RTX 3070 (see revoxhere/duino-coin#566)
- OpenCL is an optional component, so people with no OpenCL can call `make nonceMiner CFLAGS='-D NO_OPENCL'` or something

### CODE REVIEW

**Comment by YeahNotSewerSide** [comment]
That hashrate, first of all, was reached by mining on server, not pool. Second of all, mine with JoyBed gpu miner uses bunching of jobs to calculate on gpu, unfortunately, I wasn't been able to load maximum bunch to gpu, to minimise amount of gpu-cpu communication, due to gpu's watchdog, that was stopping gpu's driver as well as gpu itself under big load. Just as proof, SS sent by tester.
image

**Comment by YeahNotSewerSide** [comment]
By the way, just wanted to point out, proper midstate is not possible with DUCO-S1, there is not enough data in prev hash(previous hash 40 bytes) to process it as one block of sha1(64 bytes).

**Comment by colonelwatch** [comment]
Thanks for the information, really! Iget the first problem, but I'm not sure how bunching jobs is faster. Is a single job not enough work?

And, you're right about the fact that a proper midstate is impossible. Back when I realized this, I wrote a version of nonceMiner without the caching. I didn't then and still don't know why, but the performance suffers by about 10% when you take it out.

```console
colonelwatch@server-pc:~/PROJECTS/nonceMiner$ make benchmark CFLAGS="-D NO_OPENCL"
gcc src/mine_xxhash.c src/mine_DUCO_S1.c src/utils/table.c src/utils/xxhash.c src/utils/counter.c test/benchmark.c -O3 -Wall -o bin/benchmark -lcrypto -lOpenCL -D CL_TARGET_OPENCL_VERSION=120 -lm -D NO_OPENCL
colonelwatch@server-pc:~/PROJECTS/nonceMiner$ bin/benchmark
Benchmarking mine_DUCO_S1... Passed, with speed 7.59 +/- 0.0054 MH/s
Approximate four-core performance: 30.36 +/- 0.0217 MH/s
Benchmarking xxhash... Passed, with speed 41.08 +/- 0.0414 MH/s
Approximate four-core performance: 164.31 +/- 0.1654 MH/s
colonelwatch@server-pc:~/PROJECTS/nonceMiner$ vim src/mine_DUCO_S1.c
colonelwatch@server-pc:~/PROJECTS/nonceMiner$ make benchmark CFLAGS="-D NO_OPENCL"
gcc src/mine_xxhash.c src/mine_DUCO_S1.c src/utils/table.c src/utils/xxhash.c src/utils/counter.c test/benchmark.c -O3 -Wall -o bin/benchmark -lcrypto -lOpenCL -D CL_TARGET_OPENCL_VERSION=120 -lm -D NO_OPENCL
colonelwatch@server-pc:~/PROJECTS/nonceMiner$ ./bin/benchmark
Benchmarking mine_DUCO_S1... Passed, with speed 7.03 +/- 0.0033 MH/s
Approximate four-core performance: 28.12 +/- 0.0131 MH/s
Benchmarking xxhash... Passed, with speed 41.08 +/- 0.0414 MH/s
Approximate four-core performance: 164.31 +/- 0.1654 MH/s
```

The difference wasn't nearly as dramatic as I expected, but it was absolutely significant. I don't know what, and it definitely isn't the state itself, but it is getting cached and that saves instructions.

**Comment by YeahNotSewerSide** [comment]
The version with update you have now, save you time with memory copying,last hash,or some inside openssl structure probably, so when you use update functionality, you actually save some memory copy calls, that makes it faster. 
I used bunching to lower amount of data passing to gpu, so you can use ~157 bytes sent to gpu, while gpu will process bunch_size*workgroup_size of hashes, that reduces gpu-cpu communication a lot, that interaction between gpu-cpu in pyopencl(python binding for opencl) uses a lot of cpu time. By the way, "midstate" implemented on gpu shows worse result than implementation without it, probably due to memory usage, less memory you use on gpu-better. Hope I answered your questions.

**Comment by colonelwatch** [comment]
Yes, thanks for taking the time to answer! And it does seem that we've taken different approaches to reducing the data to the GPU.

Edit: I do think that "midstate" can work though. Just like how the prefix can be __constant in the OpenCL kernel, the "midstate" can be __constant too. That solves the memory issue. However, I didn't use a SHA1 implementation that exposes the state/context, and all this assumes that a new implementation behaves like OpenSSL.

**Comment by YeahNotSewerSide** [comment]
Actually, I used similar approach initially in miner, but pyopencl was loading cpu too much with frequent sending/enquing data to/from gpu,creating bottle neck, so I had to implement batching to decrease amount of transferred data as much as possible and make gpu to make all the work. There is a way to implement caching in "Message scheduling", but "conventional" midstate on gpu will not benefit, because update function in most of the implementations just accumulates data, and if it's more or even with 64 bytes processes 1 block, changing state, and I already tested that implementation of update function, and it truly slows it down.

**Pull request merged**
